import React, {MouseEvent, useState} from 'react'
import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useRouter} from "next/router";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [state, setState] = useState<any>({
        amount: 100,
        currency: "SGD",
        frequency: "weekly",
        description: 'Weekly subscription for goods'
    })
    const Router = useRouter();
    const startLink = (e: MouseEvent<HTMLButtonElement>) => {
        e.preventDefault()
        console.log('start linking')
    }

    const createPatLink = async () => {
        const consentUrl = await (
            await fetch("merchant-pat-link/api/link", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Follow": "true"
                },
                body: JSON.stringify({
                    amount: state.amount,
                    currency: state.currency,
                    description: state.description,
                    frequency: state.frequency
                }),
            })
        ).text();

        window.location.href = consentUrl
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.formLine}>
                    <label htmlFor="currency">Currency: </label>
                    <br/>

                    <input id="currency" name="currency" type="text"
                           value={state.currency}
                           onChange={e => setState({...state, currency: e.target.value})}

                    />
                </div>
                <br/>
                <div className={styles.formLine}>
                    <label htmlFor="amount">Amount: </label>
                    <br/>
                    <input type="text" id="amount" name="amount"
                           value={state.amount}
                           onChange={e => setState({...state, amount: e.target.value})}
                    />
                </div>
                <br/>
                <div className={styles.formLine}>
                    <label htmlFor="description">Description: </label>
                    <br/>

                    <textarea cols={40} rows={5} id="description" name="description"
                              value={state.description}
                              onChange={e => setState({...state, description: e.target.value})}

                    />
                </div>
                <br/>
                <div className={styles.formLine}>
                    <label htmlFor="frequency">Frequency: </label>
                    <br/>
                    <select id="frequency" name="frequency"
                            value={state.frequency}
                            onChange={e => setState({...state, frequency: e.target.value})}

                    >
                        <option value="weekly">weekly</option>
                        <option value="monthly">monthly</option>
                        <option value="yearly">yearly</option>
                    </select>
                </div>
                <br/>
                <div className={styles.formLine}>
                    <button className={styles.submitButton} onClick={createPatLink}>Submit</button>
                </div>
            </main>
        </>
    )
}
