import React, {MouseEvent, useState} from 'react'
import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useRouter} from "next/router";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [state, setState] = useState<any>({
        amount: 100,
        currency: "SGD",
        frequency: "weekly",
        reason: 'Weekly subscription for goods'
    })
    const Router = useRouter();
    const startLink = (e: MouseEvent<HTMLButtonElement>) => {
        e.preventDefault()
        console.log('start linking')
    }

    const onPayClick = async () => {
        const transaction = await (
            await fetch("/api/link", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Follow": "true"
                },
                body: JSON.stringify({
                    amount: state.amount,
                    currency: state.currency,
                    reason: state.reason,
                    frequency: state.frequency

                }),
            })
        ).text();
        Router.push(transaction);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <label htmlFor="currency">Currency</label>
                <input id="currency" name="currency" type="text"
                       value={state.currency}
                       onChange={e => setState({...state,  currency: e.target.value})}

                />
                <label htmlFor="amount">Amount:</label>
                <input type="text" id="amount" name="amount"
                       value={state.amount}
                       onChange={e => setState({...state,  amount: e.target.value})}
                />
                <label htmlFor="description">Reason:</label>
                <input type="text" id="reason" name="reason"
                       value={state.reason}
                       onChange={e => setState({...state,  reason: e.target.value})}

                />
                <label htmlFor="frequency">Frequency:</label>
                <select id="frequency" name="frequency"
                        value={state.frequency}
                        onChange={e => setState({...state,  frequency: e.target.value})}

                >
                    <option value="weekly">weekly</option>
                    <option value="monthly">monthly</option>
                    <option value="yearly">yearly</option>
                </select>
                <button onClick={onPayClick}>Submitttt</button>
            </main>
        </>
    )
}
