version: "3"
services:
  account-integration-sample:
    build: ./account-integration-sample
    environment:
      - ACCOUNT_CLIENT_ID=6cjlneo78ekj36l9hce1lkhb68
      - ACCOUNT_CLIENT_SECRET=hvsd42o94vg0tq5n5cvqrpdko2j4ll5ma7dgtlr7cdhgvlojlmk
      - OF_API_URL=https://api.dev.openfabric.co
      - OF_AUTH_URL=https://auth.dev.openfabric.co/oauth2/token
    ports:
      - "3001:3001"
    container_name: account-integration-sample
    restart: always
    links:
      - ngrok-account-server

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_PROTOCOL: https
      NGROK_PORT: account-integration-sample:3001
      NGROK_AUTH: 1QUmEI5PjMJt9RsEuCS7gMjGqKQ_3g7ohQqwuUPFKxXSyREQy
    container_name: ngrok-account-server
    depends_on:
      - account-integration-sample

  merchant-integration-samples:
    build:
      context: ./merchant-integration-samples/frontend-sample
      args:
        - PAYMENT_METHODS=dynamic-sample-at
        - ENV=dev
    environment:
      - OF_OAUTH_ENDPOINT=https://auth.dev.openfabric.co/oauth2/token
      - OF_API_ENDPOINT=https://api.dev.openfabric.co
      - MERCHANT_CLIENT_ID=ipk0t3mvk80ttvh4ucdbvcr33
      - MERCHANT_CLIENT_SECRET=1f9uvh9ljkavak702ffnlsnc0hr4f0h4n0d2bebdugbaoeot1fpd
    ports:
      - "3000:3000"
    container_name: merchant-server
    restart: always
