version: "3"
services:
  account-integration-sample:
    build: ./account-integration-sample
    environment:
      - ACCOUNT_CLIENT_ID=${ACCOUNT_CLIENT_ID}
      - ACCOUNT_CLIENT_SECRET=${ACCOUNT_CLIENT_SECRET}
      - OF_API_URL=${OF_API_URL}
      - OF_AUTH_URL=${OF_AUTH_URL}
      - ENV=${ENV}
      - OF_ISSUER_URL=${OF_ISSUER_URL}
      - ACCOUNT_SERVER_URL=${ACCOUNT_SERVER_URL}
      - MERCHANT_SERVER_URL=${MERCHANT_SERVER_URL}
    ports:
      - "3001:3001"
    container_name: account-integration-sample
    restart: always

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_PROTOCOL: https
      NGROK_PORT: account-integration-sample:3001
    container_name: ngrok-account-server
    depends_on:
      - account-integration-sample
  
  ngrok-merchant:
    image: wernight/ngrok
    ports:
      - "4041:4040"
    environment:
      NGROK_PROTOCOL: https
      NGROK_PORT: merchant-integration-sample:3000
    container_name: ngrok-merchant-server
    depends_on:
      - merchant-integration-sample

  merchant-integration-sample:
    build:
      context: ./merchant-integration-sample
      args:
        - PAYMENT_GATEWAY_PUBLISH_KEY=${PAYMENT_GATEWAY_PUBLISH_KEY}
        - PAYMENT_GATEWAY_NAME=${PAYMENT_GATEWAY_NAME}
        - PAYMENT_METHODS=${PAYMENT_METHODS}
        - ENV=${ENV}
        - OF_AUTH_URL=${OF_AUTH_URL}
        - OF_API_URL=${OF_API_URL}
        - MERCHANT_CLIENT_ID=${MERCHANT_CLIENT_ID}
        - MERCHANT_CLIENT_SECRET=${MERCHANT_CLIENT_SECRET}
        - OF_ISSUER_URL=${OF_ISSUER_URL}
        - ACCOUNT_SERVER_URL=${ACCOUNT_SERVER_URL}
    ports:
      - "3000:3000"
    container_name: merchant-integration-sample
    restart: always
