version: "3"
services:
  account-integration-sample:
    build: ./account-integration-sample
    environment:
      - ACCOUNT_CLIENT_ID=${ACCOUNT_CLIENT_ID}
      - ACCOUNT_CLIENT_SECRET=${ACCOUNT_CLIENT_SECRET}
      - OF_API_URL=${OF_API_URL}
      - OF_AUTH_URL=${OF_AUTH_URL}
      - ENV=${ENV}
      - PAYMENT_GATEWAY_NAME=${PAYMENT_GATEWAY_NAME}
      - PAYMENT_GATEWAY_PUBLISH_KEY=${PAYMENT_GATEWAY_PUBLISH_KEY}
      - OF_ISSUER_URL=${OF_ISSUER_URL}
    ports:
      - "3001:3001"
    container_name: account-integration-sample
    restart: always

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_PROTOCOL: https
      NGROK_PORT: account-integration-sample:3001
    container_name: ngrok-account-server
    depends_on:
      - account-integration-sample

  merchant-integration-samples:
    build:
      context: ./merchant-integration-samples/frontend-sample
      args:
        - PAYMENT_GATEWAY_PUBLISH_KEY=${PAYMENT_GATEWAY_PUBLISH_KEY}
        - PAYMENT_GATEWAY_NAME=${PAYMENT_GATEWAY_NAME}
        - PAYMENT_METHODS=${PAYMENT_METHODS}
        - ENV=${ENV}
    environment:
      - OF_AUTH_URL=${OF_AUTH_URL}
      - OF_API_URL=${OF_API_URL}
      - MERCHANT_CLIENT_ID=${MERCHANT_CLIENT_ID}
      - MERCHANT_CLIENT_SECRET=${MERCHANT_CLIENT_SECRET}
    ports:
      - "3000:3000"
    container_name: merchant-server
    restart: always
    depends_on:
      - merchant-backend-flow-endpoint

  merchant-backend-flow-endpoint:
    build:
      context: ./merchant-integration-samples/backend-flow-endpoint
    environment:
      - ENV=${ENV}
      - OF_AUTH_URL=${OF_AUTH_URL}
      - MERCHANT_CLIENT_ID=${MERCHANT_CLIENT_ID}
      - MERCHANT_CLIENT_SECRET=${MERCHANT_CLIENT_SECRET}
      - OF_ISSUER_URL=${OF_ISSUER_URL}
    ports:
      - "8080:8080"
    container_name: merchant-backend-flow-endpoint
    restart: always
