version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-merchant-sample:
    executor: heroku/default
    steps:
      - checkout
      - run: 
          name: Push to heroku
          command: |
                heroku_url="https://heroku:$HEROKU_API_KEY@git.heroku.com/$ENV-merchant-sample.git"
                git subtree push --prefix merchant-integration-sample $heroku_url chore/heroku-deploy:main
  deploy-account-sample:
    executor: heroku/default
    steps:
      - checkout
      - run: 
          name: Push to heroku
          command: |
                heroku_url="https://heroku:$HEROKU_API_KEY@git.heroku.com/$ENV-account-sample.git"
                git subtree push --prefix account-integration-sample $heroku_url chore/heroku-deploy:main
workflows:
  sandbox-deploy:
    jobs:
      - deploy-merchant-sample:
          context:
            - heroku-sample
          environment:
            ENV: sandbox
      - deploy-account-sample:
          context:
            - heroku-sample
          environment:
            ENV: sandbox

