version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-merchant-sample:
    executor: heroku/default
    steps:
      - checkout
      - run: ls
      - heroku/install               
      - run: 
          name: Push to heroku
          command: |
                cd merchant-integration-sample
                echo ${MERCHANT_SAMPLE_ENV} | base64 --decode > .env
                heroku_url="https://heroku:$HEROKU_API_KEY@git.heroku.com/sandbox-merchant-sample.git"
                cd ..
                git subtree push --prefix merchant-integration-sample $heroku_url chore/heroku-deploy:main
workflows:
  sandbox-deploy-merchant:
    jobs:
      - deploy-merchant-sample:
          context:
            - sandbox-heroku-sample
