version: 2.1
orbs:
  node: circleci/node@5.0
  aws-cli: circleci/aws-cli@3.1.3
  slack: circleci/slack@4.4.4

jobs:
  deploy-tenant-merchant-sample:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_DEFAULT_REGION
      # - run:
      #     command: |
      #       curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-arm64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      #       sudo chmod +x /usr/local/bin/lightsailctl
      - run:
          command: |
            aws --version
            aws lightsail --version
      
workflows:
  dev-deploy:
    jobs:
      - deploy-tenant-merchant-sample:
          context:
            - dev-aws-creds
            - dev-heroku-sample
          filters:
            branches:
              only:
                - main
                - chore/migrate-heroku-to-aws