version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-merchant-sample:
    executor: heroku/default
    steps:
      - checkout
      - run: ls
      - heroku/install
      - run:
          name: Prepare envs
          command: |
                cd merchant-integration-sample
                echo ${MERCHANT_SAMPLE_ENV} | base64 --decode > .env
                echo ${NPM_KEY} | base64 --decode > .npmrc
      - run: 
          name: Push to heroku
          command: |
                cd merchant-integration-sample
                ls
                heroku_url="https://heroku:$HEROKU_API_KEY@git.heroku.com/sandbox-merchant-sample.git"
            

workflows:
  sandbox-deploy-merchant:
    jobs:
      - deploy-merchant-sample:
          context:
            - sandbox-heroku-sample
