version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-merchant-sample:
    working_directory: 
      ~/openfabric-integration-samples/merchant-integration-sample
    docker:
      - image: 'cimg/node:16.8.0'
    steps:
      - checkout:
          path: 
            ~/openfabric-integration-samples
      - run: node --version
      - heroku/deploy-via-git:
          api-key: $HEROKU_API_KEY
          app-name: sandbox-merchant-sample
          branch: chore/heroku-deploy
          post-steps:
            - run: yarn install
            - run:
              name: Prepare envs
              command: |
                echo $MERCHANT_SAMPLE_ENV | base64 --decode > .env
            - run: yarn build

workflows:
  sandbox-deploy-merchant:
    jobs:
      - deploy-merchant-sample:
        context:
          - sandbox-heroku-sample
        filters:
            branches:
              only:
                - chore/heroku-deploy
