version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-merchant-sample:
    working_directory: 
      ~/openfabric-integration-samples/merchant-integration-sample
    executor: heroku/default
    steps:
      - checkout:
          path: 
            ~/openfabric-integration-samples
      - run: ls
      - heroku/install
      - run:
          name: Prepare envs
          command: |
                echo ${MERCHANT_SAMPLE_ENV} | base64 --decode > .env
      - heroku/deploy-via-git:
          api-key: HEROKU_API_KEY
          app-name: sandbox-merchant-sample
          branch: chore/heroku-deploy
            

workflows:
  sandbox-deploy-merchant:
    jobs:
      - deploy-merchant-sample:
          context:
            - sandbox-heroku-sample
