version: 2.1
orbs:
  node: circleci/node@5.0
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
jobs:
  deploy-heroku-sample:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication:
          print-whoami: true
      - setup_remote_docker:
          version: 20.10.11
      - run: 
          name: Run heroku-deploy.sh
          command: |
                echo $ENV | base64 --decode > ./.env
                chmod +x ./heroku-deploy.sh
                ./heroku-deploy.sh
      
workflows:
  dev-deploy:
    jobs:
      - deploy-heroku-sample:
          context:
            - dev-heroku-sample
          filters:
            branches:
              only:
                - main
  sandbox-deploy:
    jobs:
      - deploy-heroku-sample:
          context:
            - sandbox-heroku-sample
          filters:
            branches:
              only:
                - release-sandbox
  prod-deploy:
    jobs:
      - deploy-heroku-sample:
          context:
            - prod-heroku-sample
          filters:
            branches:
              only:
                - release-prod