# Base image
FROM node:16.0.0

# Make folder to put our files in
RUN mkdir -p /usr/src/merchant-integration-samples
RUN mkdir -p /usr/src/merchant-integration-samples/frontend-sample

# Set working directory so that all 
# subsequent command runs in this folder
WORKDIR /usr/src/merchant-integration-samples/frontend-sample

# Copy package json and install dependencies
COPY package*.json ./
COPY *.js ./ 
COPY server ./server
COPY src ./src
COPY yarn.lock ./
RUN yarn install
# Copy our app
COPY . .
ARG PAYMENT_METHODS
ENV REACT_APP_PAYMENT_METHODS=$PAYMENT_METHODS

# Expose port to access server
EXPOSE 3000

# Command to run our app
CMD [ "yarn", "start"]