# Base image
FROM node:16.0.0

# Make folder to put our files in
RUN mkdir -p /usr/src/merchant-integration-samples
RUN mkdir -p /usr/src/merchant-integration-samples/frontend-sample

# Set working directory so that all 
# subsequent command runs in this folder
WORKDIR /usr/src/merchant-integration-samples/frontend-sample

# Copy package json and install dependencies
COPY package*.json ./
COPY *.js ./ 
COPY *.json ./ 
COPY src ./src
COPY yarn.lock ./
COPY public ./public
COPY server ./server
ARG ENV
ENV REACT_APP_ENV=$ENV
ARG PAYMENT_METHODS
ENV REACT_APP_PAYMENT_METHODS=$PAYMENT_METHODS
RUN yarn install
RUN echo "$PAYMENT_METHODS"
RUN yarn build
# Copy our app
COPY . .
RUN sed -i -e "s/{PAYMENT_METHODS}/$PAYMENT_METHODS/g" ./server/public/vanilla.html
RUN sed -i -e "s/{ENV}/$ENV/g" ./server/public/vanilla.html

# Expose port to access server
EXPOSE 3000

# Command to run our app
CMD [ "yarn", "start"]