name: Code scanning with CodeQL
on: # test and build PR on any branch
  pull_request:
    branches:
      - '**'
jobs:
  analyze:
    if: ${{ github.event_name == 'pull_request' && github.secret_source == 'Actions' }}
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript-typescript"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2